#!/usr/bin/env python

import sys

from rqt2_minio_py.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt2_minio_py'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
